### ISSUE TITLE
only registers .wsd files

### ISSUE THREAD

**Issue by alumni** [jvantuyl/sublime_diagram_plugin#18]
The plugin only registers web sequence diagram (.wsd) files. Since it uses plantuml to generate the diagrams, it could as well open all plantuml files (*.pu, *.puml, *.uml, *.plantuml).

**Comment by jvantuyl** [comment]
I'm a bit reticent to do *.uml, since that seems likely to actually contain UML markup in a lot of places.

I've added the other filetypes.  I've pushed the changes up to the develop branch.  Care to verify that this is what you were looking for?

**Comment by jvantuyl** [comment]
This was updated for everything but *.uml.
