### ISSUE TITLE
cant understand how to use this

### ISSUE THREAD

**Issue by mirkhamidov** [jvantuyl/sublime_diagram_plugin#28]
installed this plugin
Sublime 2 sees this plugin in packages list
Im trying to press cmd+m while selecting a script but nothing happens.
How to run script (plantuml)?

**Comment by jvantuyl** [comment]
I'm unsure what your problem is.  Maybe the key binding didn't take?  Try finding it in the Command Palette.  It should be listed as "Diagram: Generate Diagrams for Active View".  Is that present?

**Comment by rhnorment** [comment]
I'm in the same boat.  How do we use this?

I installed the TAR and placed it the Packages directory.  I get nothing.  Do I need to manually create key bindings for this?

**Comment by ad-m** [comment]
No this kind of action too.
![zaznaczenie_1443](https://user-images.githubusercontent.com/3618479/38337519-e3c7df74-3865-11e8-9d8e-4f552caa9bfb.png)

My user settings:
```json
{
        "jar_file": "/opt/plantuml.jar"
}
```
