### ISSUE TITLE
Sublime Text 3 Image Viewer

### ISSUE THREAD

**Issue by j5vii** [jvantuyl/sublime_diagram_plugin#31]
I would love to have this plugin utilize split views and the built in ST3 image viewer so that I could see live updates of my diagram (or updates on save) side-by-side with the plant uml.

**Comment by jvantuyl** [comment]
Hmmmmm.  I don't have time to develop this right now (and I'd need to ensure ST2 compatibility), but I'd gladly accept a submission.

**Comment by hardillb** [comment]
Pull request to cover this submitted #37 it should check for Sublime 3

**Comment by jvantuyl** [comment]
Merged as #37.
