### ISSUE TITLE
Teoz Architecture

### ISSUE THREAD

**Issue by JuanCabre** [jvantuyl/sublime_diagram_plugin#32]
Hi, I am interested in using the "teoz" engine for "multicast" events in secuences. For instance I would like to do this:

```
@startuml
!pragma teoz true
Alice -> Bob : hello
& Bob -> Charlie : hi
@enduml
```
However this is giving me an error :) Is there a way to fix it?

**Comment by JuanCabre** [comment]
I found the error:

I'll post my solution just in case someone else is having this issue:

I realized that the version cloned from github was the 7981.

To make it work I had to do 3 things:
* Download the latest version to sublime_diagram_plugin/diagram/
* Rename it to plantuml-8024.jar
* Edit the file "plantuml.py" changing the following variable: PLANTUML_VERSION = 8024

Now it is working :D
Should I make a pull request with the changes made?

**Comment by jvantuyl** [comment]
Please make a pull request, yes.  Make sure to add yourself to the "Thanks" list at the bottom of the README file.  :smile:
