### ISSUE TITLE
Generated .png are not removed

### ISSUE THREAD

**Issue by davy79** [jvantuyl/sublime_diagram_plugin#35]
The generated .png files are not cleaned up as mentioned in the documentation.

>All files are created in such a way that they will be cleaned up unless Sublime Text dies a particularly horrible death.

I'm running ST3 on Ubuntu 14.04
PlantUML build 8027

**Comment by jvantuyl** [comment]
A recent change made these persistent because people were asking for that.  I've updated the README to reflect this.

If you want them cleaned up on exit, I could make a config option for that.  Open another issue if you want that config option.
