### ISSUE TITLE
hi, you may like the new diagram syntax

### ISSUE THREAD

**Issue by qjebbs** [jvantuyl/sublime_diagram_plugin#42]
Find it [here][plugin]
[plugin]: http://www.jebbs.co/2016/02/25/sublime-text-diagram-plug-in/ "Sublime Text Diagram Plug-in"
![preview](http://www.jebbs.co/wp-content/uploads/2016/02/mult_col_view.png "preview")

**Comment by nmz787** [comment]
I do find the aforementioned syntax to perform better, I only had to add `elseif` to it's `if|while` line... but the odd thing is it will highlight "escape" characters, ex `:abc\ted|` the `\t` will be purple... but I'm not sure how to fix that at the moment. Is there any interest in incorporating their syntax file into this project? I would post an issue there, but they seem to have disabled them on their fork. This is the link to the specific file https://github.com/qjebbs/sublime_diagram_plugin/blob/master/diagram.sublime-syntax

**Comment by nmz787** [comment]
Oh, just found I could comment out this block:
```
  Escape:
    # begins with \
      - match: \\.
        scope: constant.character.escape.wsd
```
to become 
```
  # Escape:
  #   # begins with \
  #     - match: \\.
  #       scope: constant.character.escape.wsd
```

but ideally this could only fail to match if the line begins with `:`

**Comment by nmz787** [comment]
eh, I guess both yours and theirs have their own issues... not sure how to merge the good parts effectively, since this is the first time I'm playing with these sublime syntax files. If I can improve yours, I'll post some changes in a new issue.
