### ISSUE TITLE
Collections support?

### ISSUE THREAD

**Issue by Ademord** [jvantuyl/sublime_diagram_plugin#56]
The following from [PlantUML](http://plantuml.com/sequence-diagram) does not run, only because of the **collections** line

```
@startuml
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6
Foo1 -> Foo2 : To boundary
Foo1 -> Foo3 : To control
Foo1 -> Foo4 : To entity
Foo1 -> Foo5 : To database
Foo1 -> Foo6 : To collections

@enduml
```

Any help or is this not supported at all?

**Comment by jvantuyl** [comment]
I think this was because we bundled an older version of PlantUML. That’s updated next release.
