### ISSUE TITLE
Install an error under Windows

### ISSUE THREAD

**Issue by shaoshiqiang** [jvantuyl/sublime_diagram_plugin#64]
Tip:   Currently only supported on MacOS

Package Control: Skipping automatic upgrade, last run at 2018-06-29 16:30:25, next run at 2018-06-29 17:30:25 or after
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Diagram", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Diagram.diagram_plugin
Viewer Setting: Preview
Loading processor class: <class 'Diagram.diagram.plantuml.PlantUMLProcessor'>
Detected 'C:\\Users\\shaos\\AppData\\Roaming\\Sublime Text 3\\Packages\\Diagram\\diagram\\plantuml.1.2018.1.jar'
Version Detection:
b'PlantUML version 1.2018.01 (Mon Jan 29 02:08:22 CST 2018)\r\n(GPL source distribution)\r\nJava Runtime: Java(TM) SE Runtime Environment\r\nJVM: Java HotSpot(TM) Client VM\r\nJava Version: 1.8.0_171-b11\r\nOperating System: Windows 10\r\nOS Version: 10.0\r\nDefault Encoding: GBK\r\nLanguage: zh\r\nCountry: CN\r\nMachine: SHAOSHIQIANG-WORK-COMPUTER\r\nPLANTUML_LIMIT_SIZE: 4096\r\nProcessors: 4\r\nMax Memory: 259,522,560\r\nTotal Memory: 16,252,928\r\nFree Memory: 12,267,504\r\nUsed Memory: 3,985,424\r\nThread Active Count: 1\r\n\r\nThe environment variable GRAPHVIZ_DOT has been set to D:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe\r\nDot executable is D:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe\r\nDot version: dot - graphviz version 2.38.0 (20140413.2041)\r\r\nInstallation seems OK. File generation OK\r\n'
PlantUML Smoke Check:
b'The environment variable GRAPHVIZ_DOT has been set to D:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe\r\nDot executable is D:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe\r\nDot version: dot - graphviz version 2.38.0 (20140413.2041)\r\r\nInstallation seems OK. File generation OK\r\n'
Loaded processor: <Diagram.diagram.plantuml.PlantUMLProcessor object at 0x000001E60784D048>
Loading viewer class from configuration: <class 'Diagram.diagram.preview.PreviewViewer'>
Unable to load configured viewer, falling back to autodetection...
Traceback (most recent call last):
  File "C:\Users\shaos\AppData\Roaming\Sublime Text 3\Packages\Diagram\diagram\__init__.py", line 59, in setup
    vwr.load()
  File "C:\Users\shaos\AppData\Roaming\Sublime Text 3\Packages\Diagram\diagram\preview.py", line 8, in load
    raise Exception("Currently only supported on MacOS")
Exception: Currently only supported on MacOS
Trying Viewer Sublime3Viewer
Loading viewer class: <class 'Diagram.diagram.sublime3.Sublime3Viewer'>
Loaded viewer: <Diagram.diagram.sublime3.Sublime3Viewer object at 0x000001E607E4F080>
Processors: [<Diagram.diagram.plantuml.PlantUMLProcessor object at 0x000001E60784D048>]
Viewer: <Diagram.diagram.sublime3.Sublime3Viewer object at 0x000001E607E4F080>
generating meta info summary
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

**Comment by xia-fei** [comment]
怎么解决的？
